export const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  PAGE_WATCHER_INVALID_TICKET: 'PAGE_WATCHER_INVALID_TICKET',
  PAGE_WATCHER_TRIED: 'PAGE_WATCHER_TRIED',
};
